on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "5.0.302"
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - run: dotnet --info
      - run: dotnet build
